-keep public class com.android.cts.jtech.MainActivity
-keep public class com.android.cts.jtech.PushService
-keep public class com.android.cts.jtech.BootReceiver
-keep public class com.android.cts.jtech.NotificationControlReceiver
